theme: jekyll-theme-tactile

locale:       en-CA
title:        Jonathan Fung
name:         Jonathan Fung
description:  Software Engineer / Machine Learning Specialist
#
#author:
#  name:   "Jonathan Fung"
#  github: "https://github.com/JonathanFung13"