theme: jekyll-theme-tactile

plugins: jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

locale:       "en-CA"
title:        "Jonathan Fung"
name:         "Jonathan Fung"
description:  "Software Engineer / Machine Learning Specialist"

author:
  name:   "Jonathan Fung"
  github: "https://github.com/JonathanFung13"